export const START_GAME  = 'START_GAME'
export const REMOVE_TOKEN_FROM_BOARD = 'REMOVE_TOKEN_FROM_BOARD'
export const ADD_TOKEN_TO_BOARD = 'ADD_TOKEN_TO_BOARD'
export const BEGIN_PLAYER_TURN = 'BEGIN_PLAYER_TURN'
export const PLAYER_TAKE_CARD = 'PLAYER_TAKE_CARD'
export const PLAYER_RESERVE_CARD = 'PLAYER_RESERVE_CARD'
export const END_PLAYER_TURN = 'END_PLAYER_TURN'

export const ADD_PLAYER = 'ADD_PLAYER'